services:
    #service 1: definition of mysql database
    db:
      image: mysql:8
      container_name: mysql-db  
      environment:
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - "3307:3306"
      restart: always

    #service 3: definition of your spring-boot app 
    project-cloud:                        #it is just a name, which will be used only in this file.
      image: tmdstudios/project-cloud               #name of the image after dockerfile executes
      container_name: project-cloud-container  #name of the container created from docker image
      build:
        context: .                          #docker file path (. means root directory)
        dockerfile: Dockerfile              #docker file name
      ports:
        - "8081:8080"                       #docker containter port with your os port
      restart: always

      depends_on:                           #define dependencies of this app
        - db                                #dependency name (which is defined with this name 'db' in this file earlier)
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/project-cloud?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root